services:
  web:
    build: .
    container_name: rent_web
    command: gunicorn project.wsgi:application --bind 0.0.0.0:14050 --workers 4 --timeout 120 --graceful-timeout 120 --keep-alive 5 --log-level info --access-logfile - --error-logfile -
    ports:
      - "14050:14050"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings

  worker:
    build: .
    container_name: rent_celery_worker
    command: celery -A project worker --loglevel=info
    ports:
      - "6350:6350"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings

  redis:
    image: redis:7-alpine
    container_name: rent_redis
    command: redis-server --port 14051
    ports:
      - "14051:14051"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "14051", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
